#!/bin/sh
echo -e "bot start \t`date`" >> /home/pi/ArturBot/bot3/log
source /home/pi/ArturBot/bot2/BOT/bin/activate
python /home/pi/ArturBot/bot3/bot.py
echo -e "bot stop \t`date`" >> /home/pi/ArturBot/bot3/log